name: example
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  interactive_chart:
    path: ../

dev_dependencies:
  flutter_lints:

flutter:
  uses-material-design: true
